sonar.projectKey=coincube
sonar.projectName=Coincube
sonar.host.url=http://localhost:9000

# Tell the scanner the real project root is one level up
sonar.projectBaseDir=..

# Sources relative to projectBaseDir
sonar.sources=./coincube-core/src,./coincubed/src,./coincube-gui/src,./coincube-ui/src
sonar.tests=./coincube-core/src,./coincubed/src,./coincube-gui/src,./coincube-ui/src
sonar.test.inclusions=**/tests/**/*.rs,**/*_test.rs

sonar.rust.cargo.manifestPaths=Cargo.toml
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/target/**,\
  **/fuzz/**,\
  **/static/**,\
  **/*.toml,\
  **/*.md,\
  **/*.yml,\
  **/*.yaml,\
  **/tests/**,\
  **/*_test.rs,\
  **/build.rs,\
  Cargo.lock

sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=rust:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/tests/**/*.rs
sonar.issue.ignore.multicriteria.e2.ruleKey=rust:S100
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*_test.rs
sonar.issue.ignore.multicriteria.e3.ruleKey=rust:S3776
sonar.issue.ignore.multicriteria.e3.resourceKey=**/state/**/*.rs