//! Generated proto types + the request/response correlation layer
//! that sits between [`super::PhoneSigner::sign_tx`] and the framed
//! transport.

use std::collections::HashMap;
use std::sync::Arc;

use tokio::sync::{oneshot, Mutex};
use tokio::task::JoinHandle;

#[allow(clippy::all, dead_code)]
pub mod local_v1 {
    // Generated by build.rs into a dedicated sub-OUT_DIR so the
    // extern-stubbed connect.v1 references don't collide with the
    // real connect.v1.rs included in `services::connect::grpc`.
    include!(concat!(
        env!("OUT_DIR"),
        "/local_envelope/coincube.local.v1.rs"
    ));
}

pub use local_v1::*;

/// Convenience alias so call sites can write `LocalEnvelope` without
/// reaching into the proto module.
pub type LocalEnvelope = local_v1::LocalEnvelope;

/// Build a [`LocalEnvelope`] carrying a `PresentSession` payload.
pub fn present_session_envelope(
    session: crate::services::connect::grpc::connect_v1::SigningSession,
) -> LocalEnvelope {
    LocalEnvelope {
        payload: Some(local_v1::local_envelope::Payload::PresentSession(
            local_v1::PresentSession {
                session: Some(session),
            },
        )),
    }
}

/// Build a [`LocalEnvelope`] carrying a `CancelSession` payload.
pub fn cancel_envelope(session_id: impl Into<String>, reason: impl Into<String>) -> LocalEnvelope {
    LocalEnvelope {
        payload: Some(local_v1::local_envelope::Payload::CancelSession(
            local_v1::CancelSession {
                session_id: session_id.into(),
                reason: reason.into(),
            },
        )),
    }
}

/// What a reader-task envelope should do, independent of how the
/// transport pulled it off the wire. Split out so unit tests can
/// exercise the classification logic without spinning up a TLS pipe.
#[derive(Debug)]
pub enum DispatchAction {
    /// Send `SignResponse::Partial(_)` to the oneshot keyed by
    /// `session_id`.
    Partial {
        session_id: String,
        partial: PartialSignature,
    },
    /// Broadcast `SignResponse::Error(text)` to every in-flight
    /// waiter (error envelopes are not session-keyed in v1).
    BroadcastError(String),
    /// Envelope was a `SessionStatusUpdate` / `Pong` / malformed —
    /// reader continues without dispatching.
    Ignore,
}

/// Classify one incoming envelope. Pure: doesn't touch the in-flight
/// map, doesn't fire any oneshots; just returns the decision so the
/// reader task can act on it under its own lock.
pub fn classify_envelope(envelope: LocalEnvelope) -> DispatchAction {
    match envelope.payload {
        Some(local_v1::local_envelope::Payload::Partial(p)) => DispatchAction::Partial {
            session_id: p.session_id.clone(),
            partial: p,
        },
        Some(local_v1::local_envelope::Payload::Error(e)) => {
            DispatchAction::BroadcastError(format!("{}: {}", e.code, e.message))
        }
        Some(local_v1::local_envelope::Payload::StatusUpdate(_)) => DispatchAction::Ignore,
        Some(local_v1::local_envelope::Payload::Pong(_)) => DispatchAction::Ignore,
        _ => DispatchAction::Ignore,
    }
}

/// Demultiplexer over a [`super::transport::PairedReader`]. One
/// reader task pulls envelopes off the wire and dispatches each
/// `PartialSignature` / `SessionStatusUpdate` / `ErrorEnvelope` to
/// the right `sign_tx` invocation by `session_id`.
///
/// `sign_tx` registers a oneshot before sending `PresentSession` and
/// then waits on the receiver; the reader fires the matching sender
/// when the partial arrives.
pub struct Correlator {
    in_flight: Arc<Mutex<HashMap<String, oneshot::Sender<SignResponse>>>>,
    _reader: JoinHandle<()>,
}

/// What the reader hands back to a waiting `sign_tx` call.
#[derive(Debug)]
pub enum SignResponse {
    Partial(PartialSignature),
    Error(String),
    Disconnected,
}

impl Correlator {
    /// Spawn a reader task that owns `reader` outright and dispatches
    /// each `session_id`-tagged payload to its registered receiver.
    /// The reader half is moved into the task so writers using the
    /// matching `PairedWriter` never contend with `recv().await`.
    pub fn spawn(reader: super::transport::PairedReader) -> Self {
        let in_flight: Arc<Mutex<HashMap<String, oneshot::Sender<SignResponse>>>> =
            Arc::new(Mutex::new(HashMap::new()));
        let in_flight_for_reader = in_flight.clone();
        let reader = tokio::spawn(async move {
            let mut reader = reader;
            loop {
                let envelope = match reader.recv().await {
                    Ok(env) => env,
                    Err(_) => {
                        // Drain in-flight and notify each with
                        // Disconnected so callers don't hang.
                        let mut waiters = in_flight_for_reader.lock().await;
                        for (_, tx) in waiters.drain() {
                            let _ = tx.send(SignResponse::Disconnected);
                        }
                        return;
                    }
                };
                match classify_envelope(envelope) {
                    DispatchAction::Partial {
                        session_id,
                        partial,
                    } => {
                        let tx = {
                            let mut waiters = in_flight_for_reader.lock().await;
                            waiters.remove(&session_id)
                        };
                        if let Some(tx) = tx {
                            let _ = tx.send(SignResponse::Partial(partial));
                        }
                    }
                    DispatchAction::BroadcastError(text) => {
                        let mut waiters = in_flight_for_reader.lock().await;
                        for (_, tx) in waiters.drain() {
                            let _ = tx.send(SignResponse::Error(text.clone()));
                        }
                    }
                    DispatchAction::Ignore => {}
                }
            }
        });
        Self {
            in_flight,
            _reader: reader,
        }
    }

    /// Register a oneshot for the given `session_id`. The matching
    /// `Partial`/`Error` from the reader will fire it.
    pub async fn register(&self, session_id: String) -> oneshot::Receiver<SignResponse> {
        let (tx, rx) = oneshot::channel();
        self.in_flight.lock().await.insert(session_id, tx);
        rx
    }

    /// Drop the registration for `session_id` (e.g. on cancel).
    pub async fn cancel(&self, session_id: &str) {
        self.in_flight.lock().await.remove(session_id);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn partial_envelope(session_id: &str, psbt: &[u8]) -> LocalEnvelope {
        LocalEnvelope {
            payload: Some(local_v1::local_envelope::Payload::Partial(
                local_v1::PartialSignature {
                    session_id: session_id.into(),
                    signed_psbt: psbt.into(),
                    signed_key_ids: Vec::new(),
                },
            )),
        }
    }

    fn error_envelope(code: &str, message: &str) -> LocalEnvelope {
        LocalEnvelope {
            payload: Some(local_v1::local_envelope::Payload::Error(
                local_v1::ErrorEnvelope {
                    code: code.into(),
                    message: message.into(),
                    session_id: String::new(),
                },
            )),
        }
    }

    fn status_envelope(session_id: &str) -> LocalEnvelope {
        LocalEnvelope {
            payload: Some(local_v1::local_envelope::Payload::StatusUpdate(
                local_v1::SessionStatusUpdate {
                    session_id: session_id.into(),
                    status: 0,
                },
            )),
        }
    }

    fn pong_envelope() -> LocalEnvelope {
        LocalEnvelope {
            payload: Some(local_v1::local_envelope::Payload::Pong(
                crate::services::connect::grpc::connect_v1::Pong { ts_unix_ms: 0 },
            )),
        }
    }

    #[test]
    fn classify_partial_routes_to_session_id() {
        let env = partial_envelope("sess-123", &[1, 2, 3]);
        match classify_envelope(env) {
            DispatchAction::Partial {
                session_id,
                partial,
            } => {
                assert_eq!(session_id, "sess-123");
                assert_eq!(partial.signed_psbt, vec![1, 2, 3]);
            }
            other => panic!("expected Partial, got {:?}", other),
        }
    }

    #[test]
    fn classify_error_broadcasts_with_combined_message() {
        let env = error_envelope("USER_DECLINED", "tap reject");
        match classify_envelope(env) {
            DispatchAction::BroadcastError(text) => {
                assert!(
                    text.contains("USER_DECLINED") && text.contains("tap reject"),
                    "expected combined text, got: {}",
                    text
                );
            }
            other => panic!("expected BroadcastError, got {:?}", other),
        }
    }

    #[test]
    fn classify_status_update_is_ignored() {
        let env = status_envelope("sess-1");
        assert!(matches!(classify_envelope(env), DispatchAction::Ignore));
    }

    #[test]
    fn classify_pong_is_ignored() {
        let env = pong_envelope();
        assert!(matches!(classify_envelope(env), DispatchAction::Ignore));
    }

    #[test]
    fn classify_empty_envelope_is_ignored() {
        // Wire could deliver an envelope with no oneof set (e.g.
        // unknown variant from a newer phone). The reader must not
        // panic on it.
        let env = LocalEnvelope { payload: None };
        assert!(matches!(classify_envelope(env), DispatchAction::Ignore));
    }
}
