//! Repository tasks, run with `cargo xtask <task>` (alias in `.cargo/config.toml`).
//!
//! `gen-images` renders the installer template images from `liana-ui/static/images/templates/`
//! into `liana-ui/static/images/generated/` and rewrites their accessors in
//! `liana-ui/src/image/template_images.rs`. The outputs are committed; CI runs `--check`.

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, ExitCode, Stdio},
};

use serde::Deserialize;

const USAGE: &str = "\
Usage: cargo xtask <task> [options]

Tasks:
  gen-images  Render the localized installer template images with Typst and refresh
              their Rust accessors. The outputs are committed; CI checks they are current.
    --check                          Verify the committed outputs, write nothing.
    --lang TAG                       Only render this locale (repeatable).
    --template ID                    Only render this template (repeatable).
    --typst PATH                     Typst executable (default: $TYPST, then `typst` on PATH).
    --allow-typst-version-mismatch   Render with a Typst that is not the pinned version.
  help        Show this message.";

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();
    let result = match args.first().map(String::as_str) {
        Some("gen-images") => gen_images::run(&args[1..]),
        None | Some("help" | "--help" | "-h") => {
            println!("{USAGE}");
            Ok(())
        }
        Some(task) => Err(format!("unknown task `{task}`\n\n{USAGE}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("error: {message}");
            ExitCode::FAILURE
        }
    }
}

/// Repository root, whatever the current directory.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives one level below the repository root")
        .to_path_buf()
}

/// Path for messages: relative to the root, forward slashes.
fn display(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn join_errors(errors: Vec<String>) -> Result<(), String> {
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("\n"))
    }
}

mod gen_images {
    use super::*;

    /// Typst output changes between versions, and CI compares bytes.
    pub const TYPST_VERSION: &str = "0.15.1";
    const TEMPLATES_DIR: &str = "liana-ui/static/images/templates";
    const GENERATED_DIR: &str = "liana-ui/static/images/generated";
    const RUST_MODULE: &str = "liana-ui/src/image/template_images.rs";
    /// System fonts are ignored: every machine renders the same bytes.
    const FONT_DIRS: &[&str] = &["liana-ui/static/fonts", "liana-ui/static/icons"];
    /// Reference for key parity, and the runtime fallback.
    const SOURCE_LOCALE: &str = "en";
    const SVG_HEADER: &str = "<!-- Generated by `cargo xtask gen-images` from \
liana-ui/static/images/templates/. Do not edit by hand. -->\n";
    const KEY_KINDS: &[&str] = &["primary", "recovery", "inheritance"];
    const SEGMENT_STATES: &[&str] = &["spend", "locked"];

    pub fn run(args: &[String]) -> Result<(), String> {
        let options = Options::parse(args)?;
        let root = repo_root();
        let templates_dir = root.join(TEMPLATES_DIR);

        let locales = Locales::load(&root, &templates_dir.join("locales"))?;
        let specs = Spec::load_all(&root, &templates_dir.join("specs"))?;
        join_errors(
            specs
                .iter()
                .flat_map(|spec| spec.validate(&locales))
                .collect(),
        )?;

        let tags = select(locales.tags(), &options.langs, "locale")?;
        let ids = select(
            specs.iter().map(|spec| spec.id.as_str()),
            &options.templates,
            "template",
        )?;

        let typst = Typst::locate(options.typst.as_deref());
        typst.check_version(options.allow_version_mismatch)?;
        let font_dirs: Vec<PathBuf> = FONT_DIRS.iter().map(|dir| root.join(dir)).collect();

        let mut sync = Sync::new(root.clone(), options.check);
        for id in &ids {
            for tag in &tags {
                let svg = pixel_size(&typst.render(&templates_dir, &font_dirs, id, tag)?);
                let path = root.join(GENERATED_DIR).join(tag).join(format!("{id}.svg"));
                sync.file(path, format!("{SVG_HEADER}{svg}").into_bytes())?;
            }
        }

        if options.langs.is_empty() && options.templates.is_empty() {
            let module = rustfmt(&root, &rust_module(&specs, &locales))?;
            sync.file(root.join(RUST_MODULE), module.into_bytes())?;
            sync.prune(&root.join(GENERATED_DIR))?;
        } else {
            println!("note: partial run, the Rust module and stale-file pruning are skipped");
        }
        sync.finish()
    }

    #[derive(Default)]
    struct Options {
        check: bool,
        langs: BTreeSet<String>,
        templates: BTreeSet<String>,
        typst: Option<PathBuf>,
        allow_version_mismatch: bool,
    }

    impl Options {
        fn parse(args: &[String]) -> Result<Self, String> {
            let mut options = Self::default();
            let mut args = args.iter();
            while let Some(arg) = args.next() {
                match arg.as_str() {
                    "--check" => options.check = true,
                    "--allow-typst-version-mismatch" => options.allow_version_mismatch = true,
                    "--lang" => {
                        options.langs.insert(value(&mut args, arg)?);
                    }
                    "--template" => {
                        options.templates.insert(value(&mut args, arg)?);
                    }
                    "--typst" => options.typst = Some(PathBuf::from(value(&mut args, arg)?)),
                    other => return Err(format!("unknown option `{other}`\n\n{USAGE}")),
                }
            }
            if options.check && options.allow_version_mismatch {
                return Err(
                    "--check compares against files rendered with the pinned Typst version, \
                     so it cannot be combined with --allow-typst-version-mismatch"
                        .into(),
                );
            }
            Ok(options)
        }
    }

    fn value<'a>(
        args: &mut impl Iterator<Item = &'a String>,
        flag: &str,
    ) -> Result<String, String> {
        args.next()
            .cloned()
            .ok_or_else(|| format!("`{flag}` expects a value\n\n{USAGE}"))
    }

    /// Requested items in the available order, or everything.
    fn select<'a>(
        available: impl Iterator<Item = &'a str>,
        requested: &BTreeSet<String>,
        what: &str,
    ) -> Result<Vec<&'a str>, String> {
        let available: Vec<&str> = available.collect();
        if requested.is_empty() {
            return Ok(available);
        }
        let unknown: Vec<&str> = requested
            .iter()
            .map(String::as_str)
            .filter(|item| !available.contains(item))
            .collect();
        if !unknown.is_empty() {
            return Err(format!(
                "unknown {what}(s) {unknown:?}; available: {available:?}"
            ));
        }
        Ok(available
            .into_iter()
            .filter(|item| requested.contains(*item))
            .collect())
    }

    /// Sorted `.toml` files of a directory, with their stem.
    fn toml_files(root: &Path, dir: &Path) -> Result<Vec<(String, PathBuf)>, String> {
        let entries = fs::read_dir(dir)
            .map_err(|err| format!("cannot read {}: {err}", display(root, dir)))?;
        let mut files = Vec::new();
        for entry in entries {
            let path = entry
                .map_err(|err| format!("cannot read {}: {err}", display(root, dir)))?
                .path();
            if path.extension().is_some_and(|ext| ext == "toml") {
                let stem = path
                    .file_stem()
                    .and_then(|stem| stem.to_str())
                    .ok_or_else(|| format!("{}: invalid file name", display(root, &path)))?
                    .to_owned();
                files.push((stem, path));
            }
        }
        files.sort();
        Ok(files)
    }

    /// One locale: section, key, text. `common` is shared; a template section holds its own.
    type Catalog = BTreeMap<String, BTreeMap<String, String>>;

    struct Locales {
        catalogs: BTreeMap<String, Catalog>,
    }

    impl Locales {
        fn load(root: &Path, dir: &Path) -> Result<Self, String> {
            let mut catalogs = BTreeMap::new();
            for (tag, path) in toml_files(root, dir)? {
                validate_tag(&tag).map_err(|err| format!("{}: {err}", display(root, &path)))?;
                let text = fs::read_to_string(&path)
                    .map_err(|err| format!("cannot read {}: {err}", display(root, &path)))?;
                let catalog: Catalog = toml::from_str(&text).map_err(|err| {
                    format!(
                        "{}: {err} (expected `[section]` tables of `key = \"text\"` entries)",
                        display(root, &path)
                    )
                })?;
                catalogs.insert(tag, catalog);
            }
            if !catalogs.contains_key(SOURCE_LOCALE) {
                return Err(format!(
                    "{}: missing the source locale `{SOURCE_LOCALE}.toml`",
                    display(root, dir)
                ));
            }
            let locales = Self { catalogs };
            locales.validate()?;
            Ok(locales)
        }

        /// Same keys as the source locale, none empty: an image never mixes languages.
        fn validate(&self) -> Result<(), String> {
            let source = keys(&self.catalogs[SOURCE_LOCALE]);
            let mut errors = Vec::new();
            for (tag, catalog) in &self.catalogs {
                for (section, entries) in catalog {
                    for (key, text) in entries {
                        if text.trim().is_empty() {
                            errors.push(format!("locale `{tag}`: `{section}.{key}` is empty"));
                        }
                    }
                }
                let keys = keys(catalog);
                for missing in source.difference(&keys) {
                    errors.push(format!(
                        "locale `{tag}`: missing `{missing}` (present in `{SOURCE_LOCALE}`)"
                    ));
                }
                for extra in keys.difference(&source) {
                    errors.push(format!(
                        "locale `{tag}`: unknown `{extra}` (absent from `{SOURCE_LOCALE}`)"
                    ));
                }
            }
            join_errors(errors)
        }

        fn tags(&self) -> impl Iterator<Item = &str> {
            self.catalogs.keys().map(String::as_str)
        }

        /// Whether the source locale defines `key`, in the template section or in `common`.
        fn defines(&self, template: &str, key: &str) -> bool {
            let catalog = &self.catalogs[SOURCE_LOCALE];
            [template, "common"]
                .iter()
                .any(|section| catalog.get(*section).is_some_and(|s| s.contains_key(key)))
        }
    }

    fn keys(catalog: &Catalog) -> BTreeSet<String> {
        catalog
            .iter()
            .flat_map(|(section, entries)| {
                entries.keys().map(move |key| format!("{section}.{key}"))
            })
            .collect()
    }

    /// Locale files are named by BCP 47 tag (`en`, `pt-PT`), matched verbatim at runtime.
    fn validate_tag(tag: &str) -> Result<(), String> {
        let mut parts = tag.split('-');
        let language = parts.next().unwrap_or_default();
        let language_ok =
            (2..=3).contains(&language.len()) && language.bytes().all(|b| b.is_ascii_lowercase());
        let subtags_ok = parts.all(|part| {
            (2..=8).contains(&part.len()) && part.bytes().all(|b| b.is_ascii_alphanumeric())
        });
        if language_ok && subtags_ok {
            Ok(())
        } else {
            Err(format!(
                "`{tag}` is not a BCP 47 locale tag such as `en` or `pt-PT`"
            ))
        }
    }

    /// Structure of one image; strings are referenced by key.
    #[derive(Deserialize)]
    #[serde(deny_unknown_fields)]
    struct Spec {
        /// File stem of the spec and the images, and the locale section.
        id: String,
        /// Name used in the generated doc comments.
        title: String,
        /// Left to right; each needs a `common.event_<name>` string.
        events: Vec<String>,
        /// Key of the note under the diagram, if any.
        #[serde(default)]
        footnote: Option<String>,
        policies: Vec<Policy>,
    }

    #[derive(Deserialize)]
    #[serde(deny_unknown_fields)]
    struct Policy {
        /// Key of the name shown above the chip.
        name: String,
        /// Key of the label shown in the chip.
        label: String,
        keys: Vec<Key>,
        /// `spend` or `locked` after each event, in event order.
        segments: Vec<String>,
    }

    #[derive(Deserialize)]
    #[serde(deny_unknown_fields)]
    struct Key {
        number: u32,
        kind: String,
    }

    impl Spec {
        fn load_all(root: &Path, dir: &Path) -> Result<Vec<Self>, String> {
            let mut specs = Vec::new();
            for (stem, path) in toml_files(root, dir)? {
                let text = fs::read_to_string(&path)
                    .map_err(|err| format!("cannot read {}: {err}", display(root, &path)))?;
                let spec: Spec = toml::from_str(&text)
                    .map_err(|err| format!("{}: {err}", display(root, &path)))?;
                if spec.id != stem {
                    return Err(format!(
                        "{}: `id` is `{}` but the file is named `{stem}`",
                        display(root, &path),
                        spec.id
                    ));
                }
                specs.push(spec);
            }
            if specs.is_empty() {
                return Err(format!("{}: no template spec found", display(root, dir)));
            }
            Ok(specs)
        }

        fn validate(&self, locales: &Locales) -> Vec<String> {
            let mut errors = Vec::new();
            let mut error =
                |message: String| errors.push(format!("template `{}`: {message}", self.id));
            let id_ok = !self.id.is_empty()
                && self
                    .id
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_');
            if !id_ok {
                error("`id` must be lowercase ASCII letters, digits and underscores".into());
            }
            if self.title.trim().is_empty() {
                error("`title` is empty".into());
            }
            if self.events.is_empty() {
                error("`events` is empty".into());
            }
            for event in &self.events {
                let key = format!("event_{event}");
                if !locales.defines(&self.id, &key) {
                    error(format!(
                        "event `{event}` needs a `{key}` string in the locales"
                    ));
                }
            }
            if let Some(footnote) = &self.footnote {
                if !locales.defines(&self.id, footnote) {
                    error(format!(
                        "footnote `{footnote}` is not defined in the locales"
                    ));
                }
            }
            if self.policies.is_empty() {
                error("`policies` is empty".into());
            }
            for (index, policy) in self.policies.iter().enumerate() {
                let policy_error = |message: String| format!("policy #{}: {message}", index + 1);
                for key in [&policy.name, &policy.label] {
                    if !locales.defines(&self.id, key) {
                        error(policy_error(format!(
                            "`{key}` is not defined in the locales"
                        )));
                    }
                }
                if policy.keys.is_empty() {
                    error(policy_error("`keys` is empty".into()));
                }
                for key in &policy.keys {
                    if !KEY_KINDS.contains(&key.kind.as_str()) {
                        error(policy_error(format!(
                            "key kind `{}` is not one of {KEY_KINDS:?}",
                            key.kind
                        )));
                    }
                    if key.number == 0 {
                        error(policy_error("key numbers start at 1".into()));
                    }
                }
                if policy.segments.len() != self.events.len() {
                    error(policy_error(format!(
                        "{} segments for {} events (one state per event)",
                        policy.segments.len(),
                        self.events.len()
                    )));
                }
                for state in &policy.segments {
                    if !SEGMENT_STATES.contains(&state.as_str()) {
                        error(policy_error(format!(
                            "segment state `{state}` is not one of {SEGMENT_STATES:?}"
                        )));
                    }
                }
            }
            errors
        }
    }

    struct Typst {
        bin: PathBuf,
    }

    impl Typst {
        fn locate(explicit: Option<&Path>) -> Self {
            let bin = explicit
                .map(Path::to_path_buf)
                .or_else(|| env::var_os("TYPST").map(PathBuf::from))
                .unwrap_or_else(|| PathBuf::from("typst"));
            Self { bin }
        }

        fn version(&self) -> Result<String, String> {
            let output = Command::new(&self.bin)
                .arg("--version")
                .output()
                .map_err(|err| {
                    format!(
                        "cannot run `{}`: {err}\nInstall Typst {TYPST_VERSION} from \
                     https://github.com/typst/typst/releases/tag/v{TYPST_VERSION}, or pass \
                     --typst PATH",
                        self.bin.display()
                    )
                })?;
            let stdout = String::from_utf8_lossy(&output.stdout);
            stdout
                .split_whitespace()
                .nth(1)
                .map(str::to_owned)
                .ok_or_else(|| format!("unexpected `typst --version` output: {stdout:?}"))
        }

        fn check_version(&self, allow_mismatch: bool) -> Result<(), String> {
            let version = self.version()?;
            if version == TYPST_VERSION {
                return Ok(());
            }
            let message = format!(
                "found Typst {version} but the images are pinned to Typst {TYPST_VERSION}, \
                 which may render them differently"
            );
            if allow_mismatch {
                eprintln!("warning: {message}");
                Ok(())
            } else {
                Err(format!(
                    "{message}\nInstall the pinned version, or pass \
                     --allow-typst-version-mismatch for a local preview."
                ))
            }
        }

        fn render(
            &self,
            templates_dir: &Path,
            font_dirs: &[PathBuf],
            template: &str,
            lang: &str,
        ) -> Result<String, String> {
            let mut command = Command::new(&self.bin);
            command
                .arg("compile")
                .arg("--root")
                .arg(templates_dir)
                .arg("--ignore-system-fonts");
            for dir in font_dirs {
                command.arg("--font-path").arg(dir);
            }
            command
                .args(["--format", "svg", "--input"])
                .arg(format!("template={template}"))
                .arg("--input")
                .arg(format!("lang={lang}"))
                .arg(templates_dir.join("render.typ"))
                .arg("-");
            let output = command
                .output()
                .map_err(|err| format!("cannot run `{}`: {err}", self.bin.display()))?;
            if !output.status.success() {
                return Err(format!(
                    "Typst failed on template `{template}`, locale `{lang}`:\n{}",
                    String::from_utf8_lossy(&output.stderr).trim()
                ));
            }
            String::from_utf8(output.stdout)
                .map_err(|_| format!("Typst produced non-UTF-8 output for `{template}`/`{lang}`"))
        }
    }

    /// Typst sizes the SVG in points; in pixels, 800 wide is the installer column, not 1066.
    fn pixel_size(svg: &str) -> String {
        let Some(start) = svg.find("<svg") else {
            return svg.to_owned();
        };
        let Some(len) = svg[start..].find('>') else {
            return svg.to_owned();
        };
        let end = start + len;
        let tag = svg[start..end].replace("pt\"", "\"");
        format!("{}{tag}{}", &svg[..start], &svg[end..])
    }

    fn rust_module(specs: &[Spec], locales: &Locales) -> String {
        let tags: Vec<&str> = locales.tags().collect();
        let mut out = String::new();
        out.push_str(
            "//! Localized installer template images.\n\
             //!\n\
             //! Generated by `cargo xtask gen-images` from `liana-ui/static/images/templates/`; \
             do not edit by hand.\n\n\
             use iced::widget::svg::Handle;\n\n\
             use crate::widget::Svg;\n\n\
             /// Locales with generated images, by tag.\n",
        );
        let list: Vec<String> = tags.iter().map(|tag| format!("{tag:?}")).collect();
        out.push_str(&format!(
            "pub const TEMPLATE_IMAGE_LOCALES: &[&str] = &[{}];\n\n",
            list.join(", ")
        ));
        out.push_str(&format!(
            "/// Locale served for any other tag.\n\
             pub const TEMPLATE_IMAGE_FALLBACK_LOCALE: &str = {SOURCE_LOCALE:?};\n\n\
             fn svg(bytes: &'static [u8]) -> Svg<'static> {{\n    \
             Svg::new(Handle::from_memory(bytes))\n}}\n"
        ));
        for spec in specs {
            out.push_str(&format!(
                "\n/// {} diagram for a locale tag such as `\"fr\"`; other tags get `{SOURCE_LOCALE}`.\n\
                 pub fn {}_template_description(locale: &str) -> Svg<'static> {{\n    \
                 let bytes: &'static [u8] = match locale {{\n",
                spec.title, spec.id
            ));
            for tag in tags.iter().filter(|tag| **tag != SOURCE_LOCALE) {
                out.push_str(&format!(
                    "        {tag:?} => include_bytes!(\"../../static/images/generated/{tag}/{}.svg\"),\n",
                    spec.id
                ));
            }
            out.push_str(&format!(
                "        _ => include_bytes!(\"../../static/images/generated/{SOURCE_LOCALE}/{}.svg\"),\n    \
                 }};\n    svg(bytes)\n}}\n",
                spec.id
            ));
        }
        out
    }

    /// So that `cargo fmt --check` accepts the generated module.
    fn rustfmt(root: &Path, source: &str) -> Result<String, String> {
        let mut child = Command::new("rustfmt")
            .args(["--edition", "2021"])
            .current_dir(root)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|err| {
                format!(
                    "cannot run rustfmt: {err} (install it with `rustup component add rustfmt`)"
                )
            })?;
        child
            .stdin
            .take()
            .expect("stdin is piped")
            .write_all(source.as_bytes())
            .map_err(|err| format!("cannot write to rustfmt: {err}"))?;
        let output = child
            .wait_with_output()
            .map_err(|err| format!("rustfmt failed: {err}"))?;
        if !output.status.success() {
            return Err(format!(
                "rustfmt rejected the generated module:\n{}",
                String::from_utf8_lossy(&output.stderr).trim()
            ));
        }
        String::from_utf8(output.stdout).map_err(|_| "rustfmt produced non-UTF-8 output".into())
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    enum Status {
        Unchanged,
        Written,
        Removed,
        Stale,
        Missing,
        Unexpected,
    }

    impl Status {
        fn label(self) -> &'static str {
            match self {
                Self::Unchanged => "unchanged",
                Self::Written => "written",
                Self::Removed => "removed",
                Self::Stale => "STALE",
                Self::Missing => "MISSING",
                Self::Unexpected => "UNEXPECTED",
            }
        }

        fn is_failure(self) -> bool {
            matches!(self, Self::Stale | Self::Missing | Self::Unexpected)
        }
    }

    /// Writes outputs, or in check mode compares them with what is committed.
    struct Sync {
        root: PathBuf,
        check: bool,
        entries: Vec<(PathBuf, Status, usize)>,
        expected: BTreeSet<PathBuf>,
    }

    impl Sync {
        fn new(root: PathBuf, check: bool) -> Self {
            Self {
                root,
                check,
                entries: Vec::new(),
                expected: BTreeSet::new(),
            }
        }

        fn file(&mut self, path: PathBuf, content: Vec<u8>) -> Result<(), String> {
            let current = fs::read(&path).ok();
            let status = if current.as_deref() == Some(content.as_slice()) {
                Status::Unchanged
            } else if self.check {
                if current.is_some() {
                    Status::Stale
                } else {
                    Status::Missing
                }
            } else {
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).map_err(|err| {
                        format!("cannot create {}: {err}", display(&self.root, parent))
                    })?;
                }
                fs::write(&path, &content)
                    .map_err(|err| format!("cannot write {}: {err}", display(&self.root, &path)))?;
                Status::Written
            };
            self.expected.insert(path.clone());
            self.entries.push((path, status, content.len()));
            Ok(())
        }

        /// Generated files nothing produces any more: removed, or reported in check mode.
        fn prune(&mut self, dir: &Path) -> Result<(), String> {
            let mut stale = Vec::new();
            walk(dir, &mut |path| {
                if !self.expected.contains(path) {
                    stale.push(path.to_path_buf());
                }
            })
            .map_err(|err| format!("cannot list {}: {err}", display(&self.root, dir)))?;
            for path in stale {
                let status = if self.check {
                    Status::Unexpected
                } else {
                    fs::remove_file(&path).map_err(|err| {
                        format!("cannot remove {}: {err}", display(&self.root, &path))
                    })?;
                    if let Some(parent) = path.parent() {
                        // Best effort.
                        let _ = fs::remove_dir(parent);
                    }
                    Status::Removed
                };
                self.entries.push((path, status, 0));
            }
            Ok(())
        }

        fn finish(self) -> Result<(), String> {
            for (path, status, size) in &self.entries {
                let size = match status {
                    Status::Removed | Status::Unexpected => String::new(),
                    _ => format!(" ({:.1} KiB)", *size as f64 / 1024.0),
                };
                println!(
                    "[{:>10}] {}{size}",
                    status.label(),
                    display(&self.root, path)
                );
            }
            let failures = self
                .entries
                .iter()
                .filter(|(_, status, _)| status.is_failure())
                .count();
            if failures > 0 {
                return Err(format!(
                    "{failures} generated file(s) out of date: run `cargo xtask gen-images` \
                     and commit the result"
                ));
            }
            if self.check {
                println!("generated files are up to date");
            }
            Ok(())
        }
    }

    fn walk(dir: &Path, visit: &mut dyn FnMut(&Path)) -> std::io::Result<()> {
        if !dir.exists() {
            return Ok(());
        }
        for entry in fs::read_dir(dir)? {
            let path = entry?.path();
            if path.is_dir() {
                walk(&path, visit)?;
            } else {
                visit(&path);
            }
        }
        Ok(())
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        fn strings(items: &[&str]) -> Vec<String> {
            items.iter().map(|item| item.to_string()).collect()
        }

        fn catalog(text: &str) -> Catalog {
            toml::from_str(text).expect("valid test catalog")
        }

        #[test]
        fn locale_tags_are_bcp47() {
            for tag in ["en", "pt-PT", "zh-Hant", "sr-Latn-RS"] {
                assert!(validate_tag(tag).is_ok(), "{tag}");
            }
            for tag in ["", "EN", "en_US", "e", "english", "en-", "fr-x"] {
                assert!(validate_tag(tag).is_err(), "{tag}");
            }
        }

        #[test]
        fn locales_mirror_the_source_locale() {
            let en = catalog("[common]\na = \"A\"\n[custom]\nb = \"B\"\n");
            let fr = catalog("[common]\na = \"Á\"\n[custom]\nb = \"Bé\"\n");
            let complete = Locales {
                catalogs: [("en".to_string(), en.clone()), ("fr".to_string(), fr)].into(),
            };
            assert!(complete.validate().is_ok());

            let fr = catalog("[common]\na = \" \"\nc = \"C\"\n");
            let broken = Locales {
                catalogs: [("en".to_string(), en), ("fr".to_string(), fr)].into(),
            };
            let errors = broken.validate().unwrap_err();
            assert!(errors.contains("`common.a` is empty"), "{errors}");
            assert!(errors.contains("missing `custom.b`"), "{errors}");
            assert!(errors.contains("unknown `common.c`"), "{errors}");
        }

        #[test]
        fn options_are_parsed() {
            let options = Options::parse(&strings(&[
                "--check",
                "--lang",
                "fr",
                "--template",
                "custom",
            ]))
            .unwrap();
            assert!(options.check);
            assert_eq!(options.langs.iter().collect::<Vec<_>>(), ["fr"]);
            assert_eq!(options.templates.iter().collect::<Vec<_>>(), ["custom"]);
            assert!(Options::parse(&strings(&["--lang"])).is_err());
            assert!(Options::parse(&strings(&["--bogus"])).is_err());
            assert!(
                Options::parse(&strings(&["--check", "--allow-typst-version-mismatch"])).is_err()
            );
        }

        #[test]
        fn selection_keeps_the_available_order() {
            let requested: BTreeSet<String> = strings(&["it", "en"]).into_iter().collect();
            let selected = select(["en", "fr", "it"].into_iter(), &requested, "locale").unwrap();
            assert_eq!(selected, ["en", "it"]);

            let unknown: BTreeSet<String> = strings(&["de"]).into_iter().collect();
            assert!(select(["en"].into_iter(), &unknown, "locale").is_err());
        }

        #[test]
        fn svg_size_is_rewritten_in_pixels() {
            let svg = "<?xml version=\"1.0\"?>\n\
                <svg class=\"typst-doc\" viewBox=\"0 0 800 320\" width=\"800pt\" height=\"320pt\">\n\
                <path d=\"M0 0\"/><text>1pt\"</text></svg>";
            let out = pixel_size(svg);
            assert!(out.contains("width=\"800\" height=\"320\""), "{out}");
            assert!(
                out.contains("<text>1pt\"</text>"),
                "only the root tag changes: {out}"
            );
            assert_eq!(pixel_size("no svg here"), "no svg here");
        }
    }
}
