//! Localized installer template images.
//!
//! Generated by `cargo xtask gen-images` from `liana-ui/static/images/templates/`; do not edit by hand.

use iced::widget::svg::Handle;

use crate::widget::Svg;

/// Locales with generated images, by tag.
pub const TEMPLATE_IMAGE_LOCALES: &[&str] = &["en", "fr", "it", "pt-PT"];

/// Locale served for any other tag.
pub const TEMPLATE_IMAGE_FALLBACK_LOCALE: &str = "en";

fn svg(bytes: &'static [u8]) -> Svg<'static> {
    Svg::new(Handle::from_memory(bytes))
}

/// Custom wallet diagram for a locale tag such as `"fr"`; other tags get `en`.
pub fn custom_template_description(locale: &str) -> Svg<'static> {
    let bytes: &'static [u8] = match locale {
        "fr" => include_bytes!("../../static/images/generated/fr/custom.svg"),
        "it" => include_bytes!("../../static/images/generated/it/custom.svg"),
        "pt-PT" => include_bytes!("../../static/images/generated/pt-PT/custom.svg"),
        _ => include_bytes!("../../static/images/generated/en/custom.svg"),
    };
    svg(bytes)
}

/// Simple inheritance diagram for a locale tag such as `"fr"`; other tags get `en`.
pub fn inheritance_template_description(locale: &str) -> Svg<'static> {
    let bytes: &'static [u8] = match locale {
        "fr" => include_bytes!("../../static/images/generated/fr/inheritance.svg"),
        "it" => include_bytes!("../../static/images/generated/it/inheritance.svg"),
        "pt-PT" => include_bytes!("../../static/images/generated/pt-PT/inheritance.svg"),
        _ => include_bytes!("../../static/images/generated/en/inheritance.svg"),
    };
    svg(bytes)
}

/// Expanding multisig diagram for a locale tag such as `"fr"`; other tags get `en`.
pub fn multisig_security_template_description(locale: &str) -> Svg<'static> {
    let bytes: &'static [u8] = match locale {
        "fr" => include_bytes!("../../static/images/generated/fr/multisig_security.svg"),
        "it" => include_bytes!("../../static/images/generated/it/multisig_security.svg"),
        "pt-PT" => include_bytes!("../../static/images/generated/pt-PT/multisig_security.svg"),
        _ => include_bytes!("../../static/images/generated/en/multisig_security.svg"),
    };
    svg(bytes)
}
