name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    env:
      BREEZ_API_KEY: ${{ github.event_name == 'push' && secrets.BREEZ_API_KEY || 'DUMMY_BREEZ_API_KEY' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.92.0
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt -- --check
      - name: clippy
        run: |
          sudo apt-get update && sudo apt-get install -y libudev-dev pkg-config protobuf-compiler libdbus-1-dev libwebkit2gtk-4.1-dev
          cargo clippy --all-targets -- -D warnings

  unit_tests:
    needs: linter
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      BREEZ_API_KEY: ${{ secrets.BREEZ_API_KEY }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - name: Test on Rust ${{ matrix.toolchain }} (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install protoc --yes --no-progress
          cargo test --no-default-features
      - name: Test on Rust ${{ matrix.toolchain }} (Unix)
        if: matrix.os == 'macOS-latest'
        env:
          PROTOC: /opt/homebrew/bin/protoc
        run: |
          brew install protobuf
          cargo test --color always -- --nocapture
      - name: Test on Rust ${{ matrix.toolchain }} (Unix)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libfontconfig1-dev pkg-config libdbus-1-dev protobuf-compiler libwebkit2gtk-4.1-dev
          cargo test --color always -- --nocapture
